name: CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Rustup
        run: rustup show

      - uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy --verbose
